//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLayerPerceptronClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLayerPerceptronClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to configuration.
        /// </summary>
        internal static string MainForm_btnCreateBack_Click_Back_to_configuration {
            get {
                return ResourceManager.GetString("MainForm_btnCreateBack_Click_Back_to_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a network.
        /// </summary>
        internal static string MainForm_btnCreateBack_Click_Create_a_network {
            get {
                return ResourceManager.GetString("MainForm_btnCreateBack_Click_Create_a_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort teaching.
        /// </summary>
        internal static string MainForm_btnTeachAbort_Click_Abort_teaching {
            get {
                return ResourceManager.GetString("MainForm_btnTeachAbort_Click_Abort_teaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach.
        /// </summary>
        internal static string MainForm_btnTeachAbort_Click_Teach {
            get {
                return ResourceManager.GetString("MainForm_btnTeachAbort_Click_Teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data file to learn!.
        /// </summary>
        internal static string MainForm_statusStripInfo_Select_data_file_to_learn {
            get {
                return ResourceManager.GetString("MainForm_statusStripInfo_Select_data_file_to_learn", resourceCulture);
            }
        }
    }
}
